services:
  api:
    build: .
    container_name: yellamma-api
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://postgres:postgres@yellamma-db:5432/yellamma
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:7-alpine
    container_name: yellamma-redis
    restart: always
  postgres:
    image: postgres:16
    container_name: yellamma-db
    restart: always
    environment:
      POSTGRES_DB: yellamma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
