services:

  api:
    build: .
    container_name: yellamma-api

    ports:
      - "8001:8000"

    volumes:
      - .:/app

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:postgres@yellamma-db:5432/yellamma
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  postgres:
    image: postgres:16

    container_name: yellamma-db

    restart: always

    environment:
      POSTGRES_DB: yellamma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
